development:
  clients:
    default:
      database: records_dev
      hosts:
        - localhost:27017
      options:
        server_selection_timeout: 1
production:
  clients:
    default:
      uri: <%= ENV['MONGOHQ_URL'] %>
      options:
        skip_version_check: true
        safe: true
