development:
  clients:
    default:
      database: records_dev
      hosts:
#        - localhost:27017
#        - ["127.0.0.1:27017"]
        - mongodb:27017
      options:
        server_selection_timeout: 1

production:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] %>
      options:
        skip_version_check: true
      safe: true
